<a href="#" id="strigger1" class="strigger sleft">&nbsp;Доставка</a>
<div id="spanel1" class="spanel sleft">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut suscipit orci. Praesent egestas fermentum consectetur. Vestibulum vulputate nibh cursus sapien sagittis egestas. Suspendisse sed magna nisi. Sed faucibus eleifend sapien ut rutrum. Phasellus sed sollicitudin ante. Integer molestie molestie tortor, feugiat porttitor elit tincidunt id. In molestie justo quis turpis feugiat vitae consequat sem vulputate. Aenean orci elit, molestie eu sollicitudin pellentesque, lobortis ultricies nisl. Donec hendrerit lacus nec sapien mattis molestie commodo leo interdum. In a mi a sem lobortis mollis id eget magna. Quisque gravida semper scelerisque. In facilisis ullamcorper consectetur. Donec ornare pretium volutpat. Mauris fermentum, nisl et vehicula congue, orci velit pellentesque nulla, varius gravida turpis libero sed neque.</p>
    <p>Suspendisse tempor, lectus non facilisis blandit, enim magna varius ipsum, sit amet blandit urna sapien et ante. Morbi ac augue eu lacus ullamcorper tincidunt. Phasellus euismod venenatis sem vel commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in augue sed augue pulvinar ultricies. Suspendisse potenti. Proin pharetra, orci fermentum vulputate suscipit, odio arcu laoreet est, eu porttitor erat elit et mi. Nullam ac erat enim, at tincidunt sapien. Donec tellus mi, ultrices vel fringilla vitae, luctus eget urna. Sed dapibus mattis massa, vel hendrerit dolor luctus vitae. Quisque at nunc arcu. Donec consequat rhoncus magna eget ultricies. Praesent felis massa, condimentum sit amet auctor venenatis, eleifend in magna.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut suscipit orci. Praesent egestas fermentum consectetur. Vestibulum vulputate nibh cursus sapien sagittis egestas. Suspendisse sed magna nisi. Sed faucibus eleifend sapien ut rutrum. Phasellus sed sollicitudin ante. Integer molestie molestie tortor, feugiat porttitor elit tincidunt id. In molestie justo quis turpis feugiat vitae consequat sem vulputate. Aenean orci elit, molestie eu sollicitudin pellentesque, lobortis ultricies nisl. Donec hendrerit lacus nec sapien mattis molestie commodo leo interdum. In a mi a sem lobortis mollis id eget magna. Quisque gravida semper scelerisque. In facilisis ullamcorper consectetur. Donec ornare pretium volutpat. Mauris fermentum, nisl et vehicula congue, orci velit pellentesque nulla, varius gravida turpis libero sed neque.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut suscipit orci. Praesent egestas fermentum consectetur. Vestibulum vulputate nibh cursus sapien sagittis egestas. Suspendisse sed magna nisi. Sed faucibus eleifend sapien ut rutrum. Phasellus sed sollicitudin ante. Integer molestie molestie tortor, feugiat porttitor elit tincidunt id. In molestie justo quis turpis feugiat vitae consequat sem vulputate. Aenean orci elit, molestie eu sollicitudin pellentesque, lobortis ultricies nisl. Donec hendrerit lacus nec sapien mattis molestie commodo leo interdum. In a mi a sem lobortis mollis id eget magna. Quisque gravida semper scelerisque. In facilisis ullamcorper consectetur. Donec ornare pretium volutpat. Mauris fermentum, nisl et vehicula congue, orci velit pellentesque nulla, varius gravida turpis libero sed neque.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut suscipit orci. Praesent egestas fermentum consectetur. Vestibulum vulputate nibh cursus sapien sagittis egestas. Suspendisse sed magna nisi. Sed faucibus eleifend sapien ut rutrum. Phasellus sed sollicitudin ante. Integer molestie molestie tortor, feugiat porttitor elit tincidunt id. In molestie justo quis turpis feugiat vitae consequat sem vulputate. Aenean orci elit, molestie eu sollicitudin pellentesque, lobortis ultricies nisl. Donec hendrerit lacus nec sapien mattis molestie commodo leo interdum. In a mi a sem lobortis mollis id eget magna. Quisque gravida semper scelerisque. In facilisis ullamcorper consectetur. Donec ornare pretium volutpat. Mauris fermentum, nisl et vehicula congue, orci velit pellentesque nulla, varius gravida turpis libero sed neque.</p>


</div>

